-- AlterTable
ALTER TABLE "ToDo" ADD COLUMN     "chatId" INTEGER,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE "ToDo" ADD CONSTRAINT "ToDo_chatId_fkey" FOREIGN KEY ("chatId") REFERENCES "ChatHistory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
